### ISSUE TITLE
Not resolvable from JCenter

### ISSUE THREAD

**Issue by tbrantb** [willis7/soapui-gradle-plugin#5]
My builds can't seem to resolve com.lv.plugins:soapui-gradle-plugin:0.1 from jcenter. How can I get this to work?

**Comment by willis7** [comment]
Hi, thanks for taking a look at the project. Currently, this project isn't functional. Ive had other distractions since starting this project, and the api has since moved to version 5. I may pick this back up in the near future. Sorry for the confusion.
